### PR TITLE
Add automatic build for Windows & MacOS version on Maven.

### PR DESCRIPTION
**Pull request by Dilandau**
I have added on pom.xml the plugins for make MacOS version & Windows version.
You can see the result on my jenkins :
https://build.mhonline.fr/job/skmclauncher/

### CODE REVIEW

**Comment by md-5** [comment]
1) You broke the pom
2) There are a few reasons to not use the launch4j maven plugin
3) Launch4j can be run standalone as shown by: http://ci.md-5.net/job/SKMCLauncher/
4) @sk89q did not want to include JavaApplicationStub since he was concerned about licensing, not sure if this is still the case.

**Comment by sk89q** [comment]
4) In lieu of no one giving me the license, my position is f\* it, let's go!

**Comment by md-5** [comment]
Since you broke this soo bad I shall manually merge it.

**Comment by md-5** [comment]
Merged: http://ci.md-5.net/job/SKMCLauncher/

**Comment by cmastudios** [comment]
@sk89q Just noticed this pull request. I posted the license to the forum post months ago. If you still need it, it is here: http://cmastudios.me/jaslicense

**Comment by md-5** [comment]
Already merged it, thanks anyway

**Pull request closed without merging**
