### PR TITLE
Allow to change configuration icons via MC update

### PR DESCRIPTION
**Pull request by dotStart**
This change allows server hosters to place a 32x32 package_icon.png in their update to use it in the launcher as configuration icon.

### CODE REVIEW

**Comment by md-5** [comment]
Can't the user pick the icon and the current one is a default only? Was @sk89q going to do more about config icons?

**Comment by dotStart** [comment]
Currently there's no way to choose the icon by yourself afaik.

**Comment by sk89q** [comment]
I want to ditch the per-configuration update files and switch to a more general list-of-configurations update files. See the PR about certificate signing.

I wouldn't mind a mailing list if anyone was up for that.

**Comment by EntityReborn** [comment]
@sk89q one thing I had in mind (slightly off topic), would be for each config, have a settingslist for each jar, so that you could have a 1.3.1 jar who's configuration never checks for updates, a 1.3.2 which adds 1.3.2 specific mods, etc.

**Comment by sk89q** [comment]
That is how it works at the moment. Make a copy of the jar and it will never update and mods are specific to that jar.

**Comment by EntityReborn** [comment]
Gah, I must have been thinking of something else. I'll look into it more.

**Comment by sk89q** [comment]
Welp I inadvertently added my own version of this.

skmclauncher_icon.png

**Pull request closed without merging**
