### PR TITLE
Use username in offline mode

### PR DESCRIPTION
**Pull request by mushroomhostage**
Sends the user's username as specified instead of Player when connecting in offline mode. 

Useful when Minecraft's login server is down (like it is right now) and you want to get to your server, or for testing with multiple players (besides your real account and Player).

Maybe this could be made into a config option if logging in as Player by default is desirable.. but this pull request just always sends the username the user specified. Other launchers do the same (e.g. Magic Launcher) with no problems..

### CODE REVIEW

**Comment by md-5** [comment]
I'm going to leave this for @sk89q to think about, as it is more a question of is it good practice or not.

**Comment by K900** [comment]
This won't work as it is now when people migrate to Mojang accounts and use emails as login names. You should store names and hashed passwords for every email that has 'remember me' on, and when offline, check if the password matches the hash and then allow to use the stored name. Something like this.

**Comment by EntityReborn** [comment]
I think this might be a good idea, as well.

**Comment by EntityReborn** [comment]
Re-PRing this as the codebase is old, and has been dirtied by other commits. In terms of @K900's comment, I will add that later, namely just by storing the authed username (requiring a valid login at least once).

**Pull request closed without merging**
