### PR TITLE
Use LWJGL 2.8.3 on Java 7 setups

### PR DESCRIPTION
**Pull request by K900**
Adds another update .xml file for lwjgl 2.8.3 and chooses it dynamically to avoid black screens of death on Java 7.

P.S. I don't have much bandwidth to host LWJGL now, so I'll appreciate it if you put it on your own server if it ever gets merged.

### CODE REVIEW

**Comment by aperson** [comment]
I would only ever use this if you scraped the lwjgl site itself to determine the latest version and download from there.  I'd be very weary of pulling files from someone's dropbox.

**Comment by sk89q** [comment]
Hmm, I don't seem to have this problem. Nevertheless, if we are to put this in, there should be a new tag added to the package format to detect Java versions. I might end up downloading the files and then signing it, and then... finding a place to put it.

**Comment by K900** [comment]
@aperson The only reason I actually extracted the package is that LWJGL only ships as a full zip with all jars, docs and natives for all architectures. The files on Dropbox are extracted from there.
@sk89q About the tag: Jens wanted to update to latest LWJGL for 1.3 so I don't see much reason in changing the format now and not using that after 1.3. Also I'm thinking the bug only exists in IcedTea7, so it shouldn't concern Windows users.

**Comment by sk89q** [comment]
Well adding another check isn't hard. The update system is supposed to be somewhat versatile anyway.

**Comment by K900** [comment]
So it's confirmed, the bug only happens on Linux with Java 7. Added a LINUX_JAVA7 platform value, now it should be working properly.

**Comment by auscompgeek** [comment]
One alternative would be to ask users of IcedTea7 (via news feed) to use latest LWJGL.

**Comment by md-5** [comment]
Not going to add.

**Pull request closed without merging**
