### PR TITLE
Backup the main minecraft jar when updating, if enabled.

### PR DESCRIPTION
**Pull request by EntityReborn**
Implements part of issue #24.

### CODE REVIEW

**Comment by nvx** [comment]
Probably more useful would be the ability to select what build of Minecraft to download, Mojang now hosts old versions of the jar for example 1.2.5 is at http://assets.minecraft.net/1_2_5/minecraft.jar

Seems like a better feature than manually backing up/etc.

**Comment by EntityReborn** [comment]
That listing only starts at 1.8pre, it seems. Also, some people might have manually patched their minecraft.jar.

**Comment by EntityReborn** [comment]
Is this not a desired function?

**Comment by brickviking** [comment]
I wrote a Linux bash script to do the downloading of various minecraft versions for me, but it would be nice to see at least the downloading functionality inside skmclauncher, given my bash script wouldn't be much use in Windows or Mac OS X.

**Pull request closed without merging**
