### PR TITLE
Added play offline options, servers.dat support, bugfix for portable mode, and an issue when running from Windows Vista and up.

### PR DESCRIPTION
**Pull request by EntityReborn**
Added a play offline option which enables the hidden checkbox already in the code, and added a second option to allow a custom username when playing offline.

### CODE REVIEW

**Comment by EntityReborn** [comment]
As I didn't see a way of messing with the server popup outside of directly editing the config file, I automatically add the servers from servers.dat, which end up making their way into the config if the configuration is saved.
Also, as there are a few places that getAbsolutePath is used when code asks for the custom base dir, pure portability wasn't guaranteed. I have fixed that here.

**Comment by md-5** [comment]
Alright, the servers.dat stuff looks promising. As does the relative path thing, I'll merge both of those manually.

I assume you want the PCA merged, is it really necessary? I use Linux most the time and had now issue when using Windows 7.

**Comment by md-5** [comment]
Merged relative pathing and servers.dat.

**Comment by EntityReborn** [comment]
Running the jar there is no issue. The issue is when you use Launch4J to create an Exe, the executable tries to do something to the JRE directory, which is a protected directory. The PCA tells the executable to not do that (or something).

**Comment by md-5** [comment]
Not going to add the offline mode stuff now, it may be considered in the future if you make a single pretty commit

**Pull request closed without merging**
